version: '3'

services:
  check-code:
    build:
      context: scripts
      dockerfile: ci-docker-images/checker/Dockerfile
    environment:
      RUSTFLAGS: "-D warnings"
    volumes:
      - $PWD:$PWD
      - ./target/cargo/registry:/root/.cargo/registry
      - ./target/cargo/git:/root/.cargo/git
    working_dir: $PWD
    user: root
    command: cargo check --all --all-targets

  check-fmt:
    build:
      context: scripts
      dockerfile: ci-docker-images/checker/Dockerfile
    volumes:
      - $PWD:$PWD
      - ./target/cargo/registry:/root/.cargo/registry
      - ./target/cargo/git:/root/.cargo/git
    working_dir: $PWD
    user: root
    command: cargo fmt -- --check

  check-style:
    build:
      context: scripts
      dockerfile: ci-docker-images/checker/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    command: ./scripts/check-style.sh

  check-generate:
    build:
      context: scripts
      dockerfile: ci-docker-images/checker/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    command: ./scripts/check-generate.sh

  check-version:
    build:
      context: scripts
      dockerfile: ci-docker-images/checker/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    command: ./scripts/check-version.rb

  check-examples:
    image: ubuntu:18.04
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    command: ["sh", "-ec", "./target/x86_64-unknown-linux-musl/release/vector validate --topology --deny-warnings ./config/examples/*.toml"]

  check-blog:
    build:
      context: scripts
      dockerfile: ci-docker-images/checker/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    command: ./scripts/check-blog-signatures.rb

  build-archive:
    build:
      context: scripts/ci-docker-images
      dockerfile: builder-x86_64-unknown-linux-musl/Dockerfile
    environment:
      TARGET: x86_64-unknown-linux-musl
      FEATURES: default-musl
      CARGO_TERM_COLOR: always
    volumes:
      - $PWD:$PWD
      - ./target/cargo/registry:/opt/rust/cargo/registry
      - ./target/cargo/git:/opt/rust/cargo/git
    working_dir: $PWD
    user: $USER
    command: make build-archive

  package-deb:
    build:
      context: scripts/ci-docker-images
      dockerfile: builder-x86_64-unknown-linux-musl/Dockerfile
    environment:
      TARGET: x86_64-unknown-linux-musl
    volumes:
      - $PWD:$PWD
      - ./target/cargo/registry:/opt/rust/cargo/registry
      - ./target/cargo/git:/opt/rust/cargo/git
    working_dir: $PWD
    command: make package-deb

  package-rpm:
    build:
      context: scripts/ci-docker-images
      dockerfile: packager-rpm/Dockerfile
    environment:
      TARGET: x86_64-unknown-linux-musl
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: make package-rpm

  verify-rpm-amazonlinux-1:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-amazonlinux-1/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "rpm -i target/artifacts/*-x86_64.rpm && vector --version"]

  verify-rpm-amazonlinux-2:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-amazonlinux-2/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "rpm -i target/artifacts/*-x86_64.rpm && vector --version"]

  verify-rpm-centos-7:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-centos-7/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "rpm -i target/artifacts/*-x86_64.rpm && vector --version"]

  verify-deb-artifact-on-deb-8:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-deb-8/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-on-deb-9:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-deb-9/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-on-deb-10:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-deb-10/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-on-ubuntu-16-04:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-ubuntu-16-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-on-ubuntu-18-04:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-ubuntu-18-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-deb-artifact-on-ubuntu-19-04:
    build:
      context: scripts/ci-docker-images
      dockerfile: verifier-ubuntu-19-04/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "dpkg -i target/artifacts/*-amd64.deb && vector --version"]

  verify-nixos:
    build:
      context: scripts
      dockerfile: ci-docker-images/verifier-nixos/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "./scripts/verify-nix.sh && vector --version"]

  target-graph:
    build:
      context: scripts/ci-docker-images
      dockerfile: target-graph/Dockerfile
    volumes:
      - $PWD:$PWD
    working_dir: $PWD

  clean:
    image: ubuntu:18.04
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    command: ["sh", "-ec", "rm -rf target"]

  init-target-dir:
    image: ubuntu:18.04
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    user: $USER
    command: ["sh", "-ec", "mkdir -p target/cargo/registry target/cargo/git"]
